services:
  mq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: spectra_test_db
      POSTGRES_USER: spectra
      POSTGRES_PASSWORD: spectra
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spectra -d spectra_test_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
  control:
    build: ./control
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${PSQL_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${PSQL_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_DATABASE_PASSWORD}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_RABBITMQ_HOST: ${RABBIT_HOST}
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}
    depends_on:
      mq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  desktop-test-agent:
    build: ./desktop-test-agent
  web-test-agent:
    build: ./web-test-agent
    env_file:
      - .env
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASSWORD}
    depends_on:
      mq:
        condition: service_healthy
    restart: unless-stopped
  mobile-test-agent:
    build: ./mobile-test-agent
    env_file:
      - .env
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASSWORD}
    depends_on:
      mq:
        condition: service_healthy
    restart: unless-stopped
volumes:
  pgdata: