services:
  mq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: spectra_test_db
      POSTGRES_USER: spectra
      POSTGRES_PASSWORD: spectra
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spectra -d spectra_test_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
  selenium-chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: "2g"
    ports: [ "4445:4444" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:4444/wd/hub/status | grep -q '\"ready\": true'" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
  selenium-firefox:
    image: seleniarm/standalone-firefox:latest
    shm_size: "2g"
    ports: [ "4446:4444" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:4444/wd/hub/status | grep -q '\"ready\": true'" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
  appium:
    image: appium/appium
    ports: ["4723:4723"]
  control:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: control
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${PSQL_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${PSQL_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PSQL_DATABASE_PASSWORD}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_RABBITMQ_HOST: ${RABBIT_HOST}
      SPRING_RABBITMQ_PORT: ${RABBIT_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}
    depends_on:
      mq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  web-test-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: web-test-agent
    env_file:
      - .env
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASSWORD}
      RABBIT_PORT: ${RABBIT_PORT}
      SELENIUM_URL_CHROME: http://selenium-chrome:4444
      SELENIUM_URL_FIREFOX: http://selenium-firefox:4444
    depends_on:
      mq:
        condition: service_healthy
      selenium-chrome:
        condition: service_healthy
      selenium-firefox:
        condition: service_healthy
    restart: unless-stopped
  mobile-test-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: mobile-test-agent
    env_file:
      - .env
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASSWORD}
      RABBIT_PORT: ${RABBIT_PORT}
      APPIUM_URL: ${APPIUM_URL}
    depends_on:
      mq:
        condition: service_healthy
      appium:
        condition: service_started
    restart: unless-stopped
volumes:
  pgdata: